# Generated by Django 5.0.1 on 2024-02-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymember', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='te',
            new_name='tel',
        ),
    ]
