# Generated by Django 5.0.1 on 2024-01-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="ip",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
