# Generated by Django 5.0.1 on 2024-01-26 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0002_memo_ip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memo",
            name="ip",
        ),
    ]
